# Generated by Django 3.2.8 on 2021-10-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_names', models.CharField(help_text="The contributor's first name or names", max_length=50)),
                ('last_names', models.CharField(help_text="The contributor's last name or names", max_length=50)),
            ],
        ),
    ]
