# Generated by Django 3.2.8 on 2021-10-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_book_coautores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='coautores',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='store.Author'),
        ),
        migrations.DeleteModel(
            name='Coautores',
        ),
    ]
